# Manages where Prism script will be loaded.
zones:
  # Load on front end pages. Defaults to true.
  frontend: true
  # Load on back end/admin pages. Defaults to false.
  backend: false

# google recaptcha api key
recaptcha_enterprise:
  key: '%env(RECAPTCHA3_KEY)%'
  google_api_key: '%env(RECAPTCHA3_SECRET)%'
  score_threshold: 0.5