### Map entities
doctrine:
  orm:
    auto_generate_proxy_classes: '%kernel.debug%'
    naming_strategy: doctrine.orm.naming_strategy.underscore
    auto_mapping: true
    mappings:
      Comment:
        is_bundle: false
        type: annotation
        dir: '%kernel.project_dir%/vendor/positron48/bolt-simple-comments/src/Entity/Comment'
        prefix: 'Positron48\CommentExtension\Entity\Comment'
        alias: Comment