### Map entities
doctrine:
  orm:
    auto_generate_proxy_classes: '%kernel.debug%'
    naming_strategy: doctrine.orm.naming_strategy.underscore
    auto_mapping: true
    mappings:
      Comment:
        is_bundle: false
        type: annotation
        dir: '%kernel.project_dir%/vendor/positron48/bolt-simple-comments/src/Entity'
        prefix: 'Positron48\Comment'
        alias: Comment

services:
  Positron48\CommentExtension\AdminMenu:
    class: \Positron48\CommentExtension\AdminMenu
    arguments: [ '@Symfony\Component\Routing\Generator\UrlGeneratorInterface' ]
    tags: [ 'bolt.extension_backend_menu' ]

  Positron48\CommentExtension\Service\CommentLoggingService:
    arguments: [ '@logger' ]

## Add the translatable labels for this extension.
framework:
  translator:
    paths: ['%kernel.project_dir%/vendor/positron48/bolt-simple-comments/translations']